spring.application.name=flight-tracker
server.port=8080

# -----------------------------------
# OPENSKY API (Live GPS Data)
# -----------------------------------
# The exact URL for New Delhi airspace we tested in Postman
opensky.api.url=https://opensky-network.org/api/states/all?lamin=28.40&lomin=76.83&lamax=28.88&lomax=77.34
opensky.api.username=YOUR_OPENSKY_CLIENT_ID
opensky.api.password=YOUR_OPENSKY_CLIENT_SECRET

# -----------------------------------
# AVIATIONSTACK API (Route Data)
# -----------------------------------
aviationstack.api.url=http://api.aviationstack.com/v1/flights
aviationstack.api.key=YOUR_AVIATIONSTACK_ACCESS_KEY
